data_gsap_chart: |
  {
    "elements": [
      "#Alcohol_LG", "#Divorced_LG", "#LGBTQ_LG", "#LowIncome_LG", "#Female_LG", "#MentalIllness_LG", "#SubstanceAbuse_LG", "#DrugUse_LG", "#Younger_LG"
    ],
    "timeline": {
      "scrollTrigger": {
        "start": "top 80%",
        "toggleActions": "play none none none"
      }
    },
    "sizeTarget": {
      "targetName": "rect",
      "sizeAttrName": "width"
    },
    "animationTargets": {
      "rect": {
        "vars": {
          "duration": 1,
          "attr": {
            "sizes": {
              "width": 0
            }
          },
          "ease": "power1.inOut"
        },
        "position": 1
      },
      "line": {
        "vars": {
          "duration": 1,
          "attr": {
            "dimensions": {
              "x1": "-=",
              "x2": "-="
            }
          },
          "ease": "power1.inOut"
        },
        "position": 1
      },
      "text": {
        "vars": {
          "duration": 1,
          "autoAlpha": 0
        },
        "position": 2
      }
    }
  }

chart_svg: |
  <?xml version="1.0" encoding="utf-8"?>
  <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
  viewBox="0 0 584 400" style="enable-background:new 0 0 584 400;" xml:space="preserve">
  <style type="text/css">
  .HRPTSD_LG_st0{opacity:0.5;}
  .HRPTSD_LG_st1{fill:none;stroke:#FFFFFF;stroke-width:2;stroke-miterlimit:10;}
  .HRPTSD_LG_st2{fill:none;stroke:#ECECEC;stroke-width:4;stroke-miterlimit:10;}
  .HRPTSD_LG_st3{fill:#ECECEC;}
  .HRPTSD_LG_st4{fill:#00090F;}
  .HRPTSD_LG_st5{font-family: 'Open Sans Condensed', 'open sans', sans-serif; font-weight: bold;}
  .HRPTSD_LG_st6{font-size:16px;}
  .HRPTSD_LG_st7{fill:#000;}
  .HRPTSD_LG_st8{font-size: 13.5px;}
  .HRPTSD_LG_st9{font-size:16px;}
  .HRPTSD_LG_st10{font-size: 14px;}
  .HRPTSD_LG_st11{fill:none;stroke:#F00024;stroke-width:5;stroke-miterlimit:10;}
  .HRPTSD_LG_st12{font-size:12px;}
  .HRPTSD_LG_st13{fill:none;stroke:#F00024;stroke-width:8;stroke-miterlimit:10;}
  </style>
  <g id="Background" class="HRPTSD_LG_st0">
  <line class="HRPTSD_LG_st1" x1="369.3" y1="397.6" x2="369.3" y2="6.9"/>
  <line class="HRPTSD_LG_st1" x1="475.7" y1="397.6" x2="475.7" y2="6.9"/>
  <line class="HRPTSD_LG_st1" x1="156.7" y1="397.6" x2="156.7" y2="6.9"/>
  <line class="HRPTSD_LG_st1" x1="581.7" y1="6.9" x2="0" y2="6.9"/>
  <line class="HRPTSD_LG_st1" x1="581.7" y1="397.6" x2="0" y2="397.6"/>
  </g>
  <g id="Baseline">
  <line class="HRPTSD_LG_st2" x1="263" y1="390" x2="263" y2="8.1"/>
  <rect x="246.8" y="2.4" class="HRPTSD_LG_st3" width="32.2" height="28"/>
  <g>
  <text transform="matrix(1 0 0 1 252.3264 22.8514)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st6">1.0</text>
  </g>
  </g>
  <g id="Alcohol_LG">
  <g>
  <text transform="matrix(1 0 0 1 28.3347 378.9871)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st8">Alcohol use disorder</text>
  <text transform="matrix(0.583 0 0 0.583 135.6819 373.4774)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st9">18#</text>
  </g>
  <g>
  <rect x="277.1" y="360" class="HRPTSD_LG_st3" width="23.5" height="26.1"/>
  <g>
  <text transform="matrix(1 0 0 1 277.9309 378.3504)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st10">1.2</text>
  </g>
  <line class="HRPTSD_LG_st11" x1="299.5" y1="386.1" x2="299.5" y2="360.1"/>
  </g>
  </g>
  <g id="Divorced_LG">
  <g>
  <text transform="matrix(1 0 0 1 84.884 336.5047)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st8">Divorced</text>
  <text transform="matrix(0.583 0 0 0.583 132.2815 330.9949)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st9">19**</text>
  </g>
  <g>
  <rect x="330.6" y="317.5" class="HRPTSD_LG_st3" width="23.5" height="26.1"/>
  <g>
  <text transform="matrix(1 0 0 1 331.3918 336.5047)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st10">1.7</text>
  </g>
  <line class="HRPTSD_LG_st11" x1="353" y1="343.6" x2="353" y2="317.6"/>
  </g>
  </g>
  <g id="LGBTQ_LG">
  <g>
  <text transform="matrix(1 0 0 1 89.8376 294.0233)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st8">LGBTQ+</text>
  <text transform="matrix(0.583 0 0 0.583 131.5842 288.5135)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st9">20††</text>
  </g>
  <g>
  <rect x="369.4" y="275.1" class="HRPTSD_LG_st3" width="36.6" height="26.1"/>
  <g>
  <text transform="matrix(1 0 0 1 371.6213 293.3865)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st12">2.0-2.1</text>
  </g>
  <line class="HRPTSD_LG_st11" x1="407.7" y1="301.2" x2="407.7" y2="275.1"/>
  </g>
  </g>
  <g id="LowIncome_LG">
  <g>
  <text transform="matrix(1 0 0 1 72.0984 251.5408)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st8">Low income</text>
  <text transform="matrix(0.583 0 0 0.583 135.6819 246.0311)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st9">18#</text>
  </g>
  <rect x="303.9" y="232.6" class="HRPTSD_LG_st3" width="99.9" height="26.1"/>
  <g>
  <text transform="matrix(1 0 0 1 334.7116 250.9051)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st10">1.4-2.3</text>
  </g>
  <line class="HRPTSD_LG_st13" x1="401.4" y1="258.7" x2="401.4" y2="232.7"/>
  </g>
  <g id="Female_LG">
  <g>
  <text transform="matrix(1 0 0 1 53.886 209.0594)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st8">Female gender</text>
  <text transform="matrix(0.583 0 0 0.583 132.282 203.5496)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st9">19**</text>
  </g>
  <rect x="353.5" y="190.1" class="HRPTSD_LG_st3" width="115.2" height="26.1"/>
  <g>
  <text transform="matrix(1 0 0 1 391.9909 208.4227)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st10">1.8-2.9</text>
  </g>
  <line class="HRPTSD_LG_st13" x1="466.3" y1="216.2" x2="466.3" y2="190.2"/>
  </g>
  <g id="MentalIllness_LG">
  <g>
  <text transform="matrix(1 0 0 1 4.4392 166.577)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st8">Diagnosed mental illness</text>
  <text transform="matrix(0.583 0 0 0.583 135.6814 161.0672)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st9">18#</text>
  </g>
  <rect x="316" y="147.6" class="HRPTSD_LG_st3" width="159.7" height="26.1"/>
  <line class="HRPTSD_LG_st13" x1="475.8" y1="173.7" x2="475.8" y2="147.7"/>
  <g>
  <text transform="matrix(1 0 0 1 376.7165 165.9412)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st10">1.5-3.0</text>
  </g>
  </g>
  <g id="SubstanceAbuse_LG">
  <g>
  <text transform="matrix(1 0 0 1 0.1008 124.0955)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st8">Substance abuse disorder</text>
  <text transform="matrix(0.583 0 0 0.583 135.6819 118.5858)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st9">18#</text>
  </g>
  <rect x="295.6" y="105.1" class="HRPTSD_LG_st3" width="232.9" height="26.1"/>
  <g>
  <text transform="matrix(1 0 0 1 392.6272 123.4588)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st10">1.3-3.5</text>
  </g>
  <line class="HRPTSD_LG_st13" x1="526.8" y1="131.2" x2="526.8" y2="105.2"/>
  </g>
  <g id="DrugUse_LG">
  <g>
  <text transform="matrix(1 0 0 1 42.175 81.2957)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st8">Drug use disorder</text>
  <text transform="matrix(0.583 0 0 0.583 135.6819 75.7859)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st9">18#</text>
  </g>
  <rect x="316" y="63" class="HRPTSD_LG_st3" width="253.3" height="26.1"/>
  <g>
  <text transform="matrix(1 0 0 1 423.176 81.2957)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st10">1.5-3.9</text>
  </g>
  <line class="HRPTSD_LG_st13" x1="568.1" y1="89.1" x2="568.1" y2="63.1"/>
  </g>
  <g id="Younger_LG">
  <g>
  <g>
  <text transform="matrix(1 0 0 1 29.8342 39.1317)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st8">Younger (&lt;65 years)</text>
  <text transform="matrix(0.583 0 0 0.583 135.6819 33.6219)" class="HRPTSD_LG_st7 HRPTSD_LG_st5 HRPTSD_LG_st9">18#</text>
  </g>
  <rect x="303.9" y="20.2" class="HRPTSD_LG_st3" width="278.1" height="26.1"/>
  <g>
  <text transform="matrix(1 0 0 1 423.8122 38.4949)" class="HRPTSD_LG_st4 HRPTSD_LG_st5 HRPTSD_LG_st10">1.4-4.0</text>
  </g>
  </g>
  <line class="HRPTSD_LG_st13" x1="580.2" y1="46.3" x2="580.2" y2="20.3"/>
  </g>
  </svg>
