name: Lighthouse Checker Manual
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Lighthouse check
  lighthouse_check:
    uses: OAPI-Commercial-IT/general-linters/.github/workflows/manual-lighthouse-checker.yml@main
    secrets: inherit